[package]
name = "qox-fdm"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
chrono = { version = "0.4", default-features = false, features = ["std", "clock"] }
libm = "0.2"
thiserror = "1"
wide = "0.7"
